---
title: ""
---
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-116712862-1"></script>
<script src="button.js"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-116712862-1');
</script>

<center  style="font-size:30px">Curriculum Vitae</center> <enter>
<center  style="font-size:10px">619 Red Cedar Road 	</center> <enter>
<center  style="font-size:10px">Michigan State University, Lansing, MI 48824</center> <enter>
<center  style="font-size:10px">E-mail: frdbrick@gmail.com</center> <enter>

<center  style="font-size:20px">EDUCATION</center>
<ul>
<li>2020 - Ph.D. Student Instructional Technology and Learning Sciences, Utah State University </li><enter>
	
<ul><li>*Advisor*: Assistant Professor Jody Clarke-Midura</li></ul> <enter>

<li>2015 -- Master of Second Language Teaching, Utah State University</li><enter>
	
<li>2007 -- B.A. Double Major Spanish Literature and Psychology, University of Colorado at Boulder</li><enter>
</ul><enter>


<center  style="font-size:20px">PUBLICATIONS</center>
<div id="myBtnContainer">
<button class="btn active" onclick="filterSelection('all')"> Show all</button>
<button class="btn" onclick="filterSelection('FLL')"> Foreign Language Learning/Teaching Articles</button>
<button class="btn" onclick="filterSelection('ET')"> Learning Sciences Articles</button>
<button class="btn" onclick="filterSelection('Games')"> Articles involving Games and Learning</button>
<button class="btn" onclick="filterSelection('Chap')">Book Chapters</button>
<button class="btn" onclick="filterSelection('Proc')">Conference Proceedings</button>
<button class="btn" onclick="filterSelection('FA')"> First Authored Articles</button>
</div>

<div class="container">
<ol reversed>

<div class="filterDiv FLL FA" ><li> In Press -- **Poole, F.** & Polio, C. From Sci-Fi to the Classroom: Implications of AI in Task-Based Writing . *Journal on Task-based Language Teaching and Learning*.3(2).
(Impact Factor=2.2)</li> </div> <enter>

<div class="filterDiv ET Games" ><li> In Press -- Folse, B & **Poole, F.**. Gamifying gamification in the sociology classroom. *Teaching Sociology*.1–13. https://doi.org/10.1177/0092055X231175176 
(Impact Factor=2.2)</li> </div> <enter>

<div class="filterDiv FLL Games FA" ><li> In Press -- **Poole, F.** & Clarke-Midura, J. Applying educational data mining to explore individual experiences in digital games. *Language Learning & Technology*.27(1), 1–26. http://hdl.handle.net/10125/73522
(Impact Factor=4.31)</li> </div> <enter>

<div class="filterDiv Proc Games FA" ><li>2023-- **Poole, F.**, & Lee, V. R. Esports athletes’ group sensemaking of team gameplay data analytics. Paper Presented at *Games, Learning and Society Proceedings*, Irvine, CA</li> </div> <enter>

<div class="filterDiv FLL FA" ><li>2022 -- **Poole, F.**. Using ChatGPT to design language material and exercise. *FLTMag*, https://fltmag.com/chatgpt-design-material-exercises/ </li> </div> <enter>

<div class="filterDiv FLL Games FA" ><li> 2022 --  **Poole, F.**, Clarke-Midura, J., & Ji, S..Exploring the Affordances and Effectiveness of a Digital Game in the Chinese Dual Language Immersion Classroom. *Journal of Technology and Chinese Language Teaching*,13(1),46-73.  </li> </div> <enter>

<div class="filterDiv FLL Games Proc" ><li> 2022 -- Nagai, T., York, J., **Poole, F.** & Nakayama, H.. Developing an AR language learning system: Comparing the effects of modality on reading comprehension, vocabulary acquisition and motivation. In T. Bastiaens (Ed.), Proceedings of *EdMedia + Innovate Learning* (pp. 388-395). New York City, NY, United States: Association for the Advancement of Computing in Education (AACE). </li> </div> <enter>

<div class="filterDiv ET Proc" ><li>2022 -- Shehzad, U., Lee, V.R., Clarke-Midura, J., Recker, Mi.,& **Poole, F.**. Authorship and intended difficulty in the context of an expansively-framed-unplugged elementary computer science unit. Paper presented at the *American Educational Research Association Conference*, San Diego, CA </li></div><enter>

<div class="filterDiv FLL Games" ><li> 2021 -- York, J., **Poole, F.**, & deHaan, J. Playing a new game: An argument for a teacher-focused field around games and play in language education. *Foreign Language Annals*,54(4), 1164-1188. (Impact Factor=2.06)</li><enter> </div>

<div class="filterDiv ET FA Games" ><li>2021 -- **Poole, F.**, Clarke-Midura, J., Rasmussen, M., Shehzad, U., & Lee, V. R. Tabletop games designed to promote computational thinking. *Computer Science Education*: DOI: 10.1080/08993408.2021.1947642(CiteScore=5.1)</li><enter></div>

<div class="filterDiv FLL FA" ><li>2021 --**Poole, F.**. Using Scratch to Teach Computer Science in the Language Classroom. *FLTMag*, November 2021. https://fltmag.com/scratch-computer-science/ </li><enter></div>

<div class="filterDiv FLL Games FA" ><li>2021 --**Poole, F.**. Co-Management: A Ludic Language Pedagogy Approach. *Ludic Language Pedagogy* (3). 48-59. </li><enter></div>

<div class="filterDiv FLL Chap" ><li>2021 -- Thoms, J. & **Poole, F.** Language teachers and the open education movement: A national survey.*Open education and foreign language learning and teaching: The rise of a new knowledge ecology.* Bristol, UK: Multilingual Matters.</li><enter></div>

<div class="filterDiv FLL Games FA" ><li> 2020 -- **Poole, F.,** & Clarke-Midura, J. A systematic review of digital games in second language learning studies. *International Journal of Game-Based Learning*, 10(3),1-15. (CiteScore = 1.27).</li><enter></div>

<div class="filterDiv FLL Games FA" ><li>2020 --**Poole, F.**. Exploring authentic language use in the classroom. *Ludic Language Pedagogy* (2). 75-85. </li><enter></div>

<div class="filterDiv ET Games Proc" ><li>2020 -- Lee, V. R., **Poole, F.**, Rasmussen, M., Clarke-Midura, J., & Recker, M. Examining Variations in Teacher Talk when Implementing New Unplugged-to-plugged Computing Instruction. *Paper presented at the American Educational Research Association Conference (AERA)*, San Francisco, CA.</li><enter></div>

<div class="filterDiv ET Games Proc" ><li>2020 --	Lee, V. R., **Poole, F.**, Clarke-Midura, J., Recker, M., Rasmussen, M. Introducing coding through tabletop board games and their digital instantiations across elementary classrooms and school libraries. *In Proceedings of the ACM Technical Symposium on Computer Science Education* (SIGCSE '20). ACM, Portland, OR, USA</li><enter></div>

<div class="filterDiv FLL Games FA" ><li>2019 -- **Poole, F.,** Clarke-Midura, J., Sun, C, & Lam, K. Exploring the pedagogical affordances of a collaborative board game in a dual language immersion classroom. *Foreign Language Annals*. 753-775 52(4). https://doi.org/10.1111/flan.12425 (Impact Factor= 1.78)</li><enter></div>

<div class="filterDiv FLL" ><li>2019 -- Walker, J., & **Poole, F.** Effects of delaying character instruction in a Chinese as second language middle school classroom. *Researching and Teaching Chinese as a Foreign Language*,2(2), 261-280. </li><enter></div>

<div class="filterDiv ET Proc" ><li>2019 -- Clarke-Midura, J., Sun, C., Pantic, K., **Poole, F.**, & Allan, V. Using Informed Design in Informal Computer Science Programs to Increase Youths’ Interest, Self-efficacy, and Perceptions of Parental Support. *ACM Transactions on Computing Education (TOCE)*, 19 (4), 1-12 (Article 37), doi: 10.1145/3319445 </li><enter></div>

<div class="filterDiv FLL" ><li>2018 -- Thoms, J., Arshavskaya, E., & **Poole, F.** Open educational resources and ESL education: Insights from educators in the United States.*TESL-EJ*, 22(2), Retrieved from http://www.tesl-ej.org/wordpress/issues/volume22/ej86/ej86a2/ </li><enter></div>

<div class="filterDiv FLL" ><li>2018 -- Thoms, J., & **Poole, F.** Exploring digital literacy practices via L2 social reading, *L2 Journal* (Special Issue), 10(2), Retrieved from https://escholarship.org/uc/item/0fk329vn </li><enter></div>

<div class="filterDiv FLL Games FA Chap" ><li>2018 -- **Poole, F.**, Franco, J., & Clarke-Midura, J. Developing a personalized, educational gaming experience for young Chinese DLI learners: A design-based approach. In R. Zheng (Ed.), *Digital Technologies and Instructional Design for Personalized Learning* (pp. 253-274). IGI Global</li><enter></div>

<div class="filterDiv ET" ><li>2018 -- Pantic, K., Clarke-Midura, J., **Poole, F.**, Roller, J, & Allan, V. Drawing a computer scientist: Stereotypical representations or lack of awareness? *Computer Science Education Journal*</li><enter></div>

<div class="filterDiv ET Proc" ><li>2018 -- Clarke-Midura, J., **Poole, F.**, Pantic, K., Sun, C., & Allan, V. How mother and father support affect youths’ interest in computer science. *In Proceedings of ACM ICER conference*, Espoo, Finland, August, 2018 </li><enter></div>

<div class="filterDiv ET Proc" ><li>2018 --	Clarke-Midura, J., **Poole, F.**, Pantic, K., Hamilton, M., Sun, C., & Allan, V. How Near Peer Mentoring Affects Middle School Mentees. *In Proceedings of the 49th ACM Technical Symposium on Computer Science Education* (SIGCSE '18). ACM, New York, NY, USA, 664-669. (Second Best Paper CS Education Research)</li><enter></div>

<div class="filterDiv FLL" ><li>2017 -- Sung, K. Y., & **Poole, F.** Investigating the use of a smartphone social networking application on language learning. *JALT CALL Journal*, 13(2), 97–115. (CiteScore= .62)</li><enter></div>

<div class="filterDiv FLL" ><li>2017 --	Thoms, J., Sung, K. Y., & **Poole, F.** Investigating the linguistic and pedagogical affordances of an L2 open reading environment via eComma: An exploratory study in a Chinese language course. *System*, 69, 38–53. (Impact Factor = 1.93)</li><enter></div>

<div class="filterDiv FLL"><li>2017 --	Thoms, J., & **Poole, F.** Investigating linguistic, literary, and social affordances of L2 collaborative reading. *Language Learning & Technology*, 21(2), 139–156. (Impact Factor = 2.13) </li><enter></div>

<div class="filterDiv ET" ><li>2017 -- Clarke-Midura, J., **Poole, F.**, Pantic, K., & Allan, V. Playing mentor: A new strategy for recruiting young women into computer science. *Journal of Women and Minorities in Science and Engineering*, 23(3). (CiteScore= 1.15)</li><enter></div>

<div class="filterDiv FLL FA" ><li>2016 --	**Poole, F.**, & Sung, K. A preliminary study on the effects of an E-gloss tool on incidental vocabulary learning when reading Chinese as a foreign language. *Journal of Chinese Language Teachers Association*. 51(3), 266–285. </li><enter></div>

<div class="filterDiv FLL" ><li>2016 -- Sung, K. Y., & **Poole, F.** Differences between native and non-native English speaking teachers in China from the perspectives of Chinese EFL students. *The Journal of English as an International Language*, 11(2), 1–18. </li><enter></div>

<div class="filterDiv FLL Chap" ><li>2016 --	Sung, K. Y., & **Poole, F.** Differences between native and non-native Chinese speaking teachers: Voices from overseas students who study Chinese in China. In C. P. Chou & J. Spangler (Eds.) *Chinese Education Models in a Global Age* (pp. 133–147). Springer, Singapore.</li><enter></div>

<div class="filterDiv FLL" ><li>2015 -- Sung, K. Y., & **Poole, F.** Evaluating the impact of graded readings on the recognition of Chinese characters and reading comprehension by learners of Chinese as a foreign language. *Konin Language Studies*, 3(3), 271–294.</li><enter></div>

<div class="filterDiv FLL FA" ><li>2015 -- **Poole, F.**, & Sung, K. Three approaches to beginning Chinese instruction and their effects on oral development and character recognition. *Eurasian Journal of Applied Linguistics*, 1(1), 59–75. </li><enter></div>

</ol>

<center  style="font-size:20px">WORKS IN PROGRESS</center>
<ol reversed>



</ol>

<center  style="font-size:20px">PROFESSIONAL AND ACADEMIC POSITIONS</center><enter>
<ul>
<li>2020 - Present – Assistant Professor, Master of Arts in Foreign Language Teaching Program, Michigan State University, Michigan, MI </li><enter>

<li>2019 - 2020 – Adjunct Instructor, Instructional Technology and Learning Sciences, Utah State University, Logan, UT </li><enter>

<li>2017 – 2018 --  Adjunct Instructor, School of Teacher Education and Leadership, Utah State University, Logan, UT </li><enter>

<li>2015 – Present --	Graduate Research Assistant, Instructional Technology and Learning Sciences Department, Utah State University, Logan, UT</li><enter>

<li>2013 – 2016 --	Graduate/Adjunct Chinese Instructor, Languages, Philosophy, and Communication Studies, Department, Utah State University, Logan, UT</li><enter>

<li>2010 – 2013 --	Director of Studies, Mercan English School, Beijing/Taiyuan, China </li><enter>

<li>2008 – 2013 --	English as a Foreign Language (EFL) Teacher, Mercan English School, Taiyuan, China</li><enter>

<li>2007 – 2008 --	Assistant Dual Language Immersion Teacher (English Teacher), Government of Andalucía, Lora del Río, Seville, Spain</li><enter>

<li>2006 --	English Teaching Assistant, English Opens Doors Program, Santiago, Chile</li>
</ul><enter>

<center  style="font-size:20px">TEACHING</center>

#### Michigan State University
<enter>
<li>Summer 2022	Foreign/Second Language Acquisition (FLT 860)</li><enter>
<li>Summer 2022	Assessment for Foreign Language Teaching (FLT 808)</li><enter>
<li>Spring 2022		Foreign/Second Language Acquisition (FLT 860)</li><enter>
<li>Spring 2022		Assessment for Foreign Language Teaching (FLT 808)</li><enter>
<li>Spring 2022		Foreign/Second Language Methods (FLT 807)</li><enter>
<li>Fall 2021		Teaching Foreign Languages with Technology (FLT 881)</li><enter>
<li>Fall 2021		Sociolinguistics & Spoken Language (FLT 841)</li><enter>
<li>Fall 2021		Foreign/Second Language Methods (FLT 807)</li><enter>
<li>Summer 2021   	Teaching Foreign Languages with Technology (FLT 881)</li><enter>
<li>Summer 2021	Foreign/Second Language Methods (FLT 807)</li><enter>
<li>Spring 2021		Foreign/Second Language Acquisition (FLT 860)</li><enter>
<li>Spring 2021		Assessment for Foreign Language Teaching (FLT 808)</li><enter>
<li>Spring 2021		Experiential Module (FLT 885)</li><enter>
<li>Fall 2020		Teaching Foreign Languages with Technology (FLT 881)</li><enter>
<li>Fall 2020		Sociolinguistics & Spoken Language (FLT 841)</li><enter>
<li>Fall 2020		Experiential Module (FLT 885)</li><enter>

</ul><enter>

#### Utah State University
<enter>
<ul>
<li>Spring 2020 -- Games and Learning (ITLS 6730) (*Graduate Level Online Course*) </li><enter>
<li>Fall 2019 -- Mobile Design and Development for Learning (ITLS 3870/5750) (*Graduate Level Online Course*)</li><enter>
<li>Spring 2019 -- Games and Learning (ITLS 6730) (*Graduate Level Online Course*)</li><enter>
<li>Fall 2017 -- Learning Theory (ITLS 6540) (*Graduate-level course, taught last 7 weeks of course at request of department due to maternity leave of a faculty member*)</li><enter>
<li>Fall 2017 -- Second Language/Literacy Acquisition and Development (TEAL 4745)</li><enter>
<li>Fall 2016 -- First-Year Chinese 1 (Chinese 1010) </li><enter>
<li>Fall 2015 -- First-Year Chinese 1 (Chinese 1010) </li><enter>
<li>Spring 2015 -- Teaching Chinese as a Foreign Language (Chinese 4100)</li><enter>
<li>Fall 2014 -- First-Year Chinese 1 (Chinese 1010) </li><enter>
<li>Spring 2014		First-Year Chinese II (Chinese 1020)</li><enter>
<li>Fall 2013 -- First-Year Chinese 1 (Chinese 1010) </li><enter>
</ul><enter>

#### Mercan School (Private EFL Institute in China)<enter>
<ul>
<li>2008 – 2013	->	TOEFL/IELTS Test Prep </li><enter>
<li>2008 – 2013	->	High School American Literature/American Culture Course </li><enter>
<li>2008 – 2013	->	Elementary Level English Course</li><enter>
</ul>

<center  style="font-size:20px">CONFERENCE PRESENTATIONS</center><enter>
<ol reversed>

<li> 2024 -- AI & TBLT Workshop for LCTL Instructors. Mellon Grant Workshop for LCTL 				Instructors hosted by CELTA at MSU [Workshop] </li> <enter>

<li> 2024 -- Integrated skills assessment and Integrate performance assessments. Ukraine Scholars			Delegation Hosted by MSU [Workshop] </li> <enter>

<li> 2024 -- Data Analytics to Explore the Impact of a Task-based Digital Game on Learners’ 				Affect. Computer Assisted Language Instruction (CALICO) Conference. [Presentation]. 		Pittsburgh, PA </li> <enter>

<li> 2024 -- Can ChatGPT Reliably Score L2 Writing Assessments? The Devil is in the Prompt. 			Computer Assisted Language Instruction (CALICO) Conference. [Presentation]. 				Pittsburgh, PA </li> <enter>

<li> 2024 -- Games for Language Learning: Connecting Industry, Research, and Practice. Computer 		Assisted Language Instruction (CALICO) Conference. [Panel]. Pittsburgh, PA </li> <enter>

<li> 2023 -- Data literacy and data-driven decision making for language teachers. American 				Association of Applied Linguistics (AAAL) Conference, Portland </li> <enter>


<li> 2022 -- Leveraging a spatial chat software to design gaming experiences for in-class instruction. JALT CALL Conference, Virtual.</li> <enter>

<li> 2022 -- Esports athletes’ group sensemaking of team gameplay data analytics. Games Learning and Society (GLS). Irvine, CA</li> <enter>

<li> 2022 -- Using Gather.Town to Re-Imagine Interaction in Virtual and Hybrid Language Learning. Midwest Association for Language Learning Technology (MWALLT) Conference, Virtual. (With Amanda Lanier and Bruna Sommer Farias)</li> <enter>

<li>2021 -- Developing Intercultural Competence through Social Justice Education. *American Council on the Teaching of Foreign Languages (ACTFL) Conference*, Virtual. (With Kaleigh Doan) </li> <enter>

<li>2021 -- Bringing Computer Science into the Language Classroom. *International Association for Language Learning Technology (IALLT) Conference*. (Virtual)</li><enter>

<li>2021 -- Applying educational data mining techniques to explore second language learning in a digital game. *American Association of Applied Linguistics (AAAL) Conference*.(Virtual)</li><enter>

<li>2021 -- Teaching languages with games: A practice-based workshop. *Computer Assisted Language Instruction (CALICO)* Winter Workshop (Virtual).</li><enter>

<li>2020 -- Analyzing Digital Social Reading Practices in an L2 Chinese Literature Course. *American Association of Applied Linguistics (AAAL) Conference*, Denver, Co,(with Dr. Joshua Thoms). – CANCELED (Covid-19) </li><enter>

<li>2019 -- A Chinese RPG Game, *Computer Assisted Language Instruction Consortium (CALICO) Conference* [Showcase Presentation], Montreal, Canada. </li><enter>

<li>2018 -- Analyzing Digital Literacy Practices via L2 Collaborative Reading. *World CALL*, Concepción, Chile (with Dr. Joshua Thoms). </li><enter>

<li>2018 -- Interactive Stories with Twine. *Computer Assisted Language Instruction Consortium (CALICO) Conference*, Urbana-Champaign, IL. </li><enter>

<li>2018 -- Using digital games in the language classroom. *Utah Foreign Language Teaching	Association (UFLA) Conference*, Ogden, UT.</li><enter>

<li>2017 -- Investigating linguistic, literary, and social affordances of L2 collaborative/social reading. *American Association of Applied Linguistics (AAAL) Conference*, Portland, OR, (with Dr. Joshua Thoms).</li><enter>

<li>2017 -- Using a story-driven game in the Chinese dual language immersion classroom. *Utah Foreign Language Teaching Association (UFLA) Conference*, Orem, UT.</li><enter>

<li>2016 -- A cross-language analysis of online language tutors’ corrective feedback and learners’ uptake when learning via videoconferencing tool. *American Association of Applied Linguistics (AAAL) Conference*, Orlando, FL.</li><enter>

<li>2016 -- Collaboration and learning with a board game in a Chinese dual language immersion classroom. *Utah Foreign Language Teaching Association (UFLA) Conference*, Orem, UT.</li><enter>

<li>2015 -- Investigating the effectiveness of 'We Chat' on language learning. *American Council on the Teaching of Foreign Languages (ACTFL) Conference*, San Diego, CA.</li><enter>

<li>2015 -- The effects of E-dictionaries on incidental vocabulary learning. *American Council on the Teaching of Foreign Languages (ACTFL) Conference*, San Diego, CA.</li><enter>
			
<li>2015 -- A new model for Chinese compliment responses. *Western Conference Association for Asian Studies (WCAAS) conference*, Salt Lake City, UT.</li><enter>

<li>2015 -- A comparison and analysis of three-character instruction approaches. *Chinese American Educational Research and Development Association (CAERDA) Conference*, Chicago, IL.</li><enter>

<li>2015 -- Practical applications for web-based tools in the Chinese classroom. *Utah Foreign Language Teaching Association (UFLA) Conference*, Ogden, UT.</li><enter>

<li>2014 -- Graded readers in the Chinese classroom. *American Council on the Teaching of Foreign Languages (ACTFL) Conference*, San Antonio, TX. </li><enter>

<li>2014 -- Effects of e-glosses on long-term retention of vocabulary when reading Chinese. *Lackstrom Symposium*, Logan, UT.</li><enter>

<li>2013 -- Integrating reading into the communicative classroom. *Intermountain Teachers of English to Speakers of Other Languages (I-TESOL) Conference*, Salt Lake City, UT.</li></ol><enter>

<center  style="font-size:20px">PROFESSIONAL ACTIVITIES/SERVICE</center><enter>
<ul>
<li>2022 -- Co-Chair, *JALT CALL Conference* </li><enter>

<li>2021 -- Manuscript Reviewer, *Language Learning & Technology* </li><enter>

<li>2021 -- Manuscript Reviewer, *System Journal* </li><enter>

<li>2021 -- Manuscript Reviewer, *International Journal of Computer-Supported Collaborative Learning* </li><enter>

<li>2020 -- Manuscript Reviewer, *Language Learning & Technology* </li><enter>

<li>2020 -- Manuscript Reviewer, *Ludic Language Pedagogy* </li><enter>

<li>2019 -- Manuscript Reviewer, *Foreign Language Annals* </li><enter>

<li>2019 -- Book Reviewer, *Language Learning & Technology* </li><enter>

<li>2018 -- Manuscript Reviewer, *Computers & Education* </li><enter>

<li>2018 -- Search Committee for Tenure-Track Position in Department of Instructional Technology and Learning Sciences at Utah State University.</li><enter>

<li>2018 -- Search Committee for Professor of Practice Position in Department of Instructional Technology and Learning Sciences at Utah State University.</li><enter>

<li>2017 -- Manuscript Reviewer, *Computers & Education* </li><enter>

<li>2017 -- Manuscript Reviewer, *Digital Technologies and Instructional Design for Personalized Learning* </li><enter>

<li>2016 -- Manuscript Reviewer, *New Waves—Educational Research and Development* </li><enter>
</ul>

<center  style="font-size:20px">AWARDS & GRANTS</center><enter>

<ol reversed>
<li>2018 -- Doctoral Student Researcher of the Year, Department of Instructional Technology and Learning Sciences, Utah State University</li><enter>

<li>2017 -- Graduate Enhancement Award (Awarded $4,000), Utah State University</li><enter>

<li>2016 -- Rick Q. Lawson Scholarship (Awarded $3,000), Emma Eccles Jones College of	Education and Human Services, Utah State University </li><enter>

<li>2016 -- Presidential Fellowship (Awarded $20,000), Department of Instructional Technology	and Learning Sciences, Utah State University </li><enter>

<li>2015 -- Rick Q. Lawson Scholarship (Awarded $1,750), Emma Eccles Jones College of Education and Human Services, Utah State University</li><enter>

<li>2015 -- TalkAbroad – Short-Term Research Grant – (Awarded \$5,000 TalkAbroad credit; $1,500 for research)</li><enter>

<li>2015 -- Pat Buckner Award for Collaborative Teaching Projects (Awarded $950), Utah Foreign Language Association</li><enter>

<li>2014 -- Graduate Researcher of the Year, Department of Languages, Philosophy, and Communication Studies, Utah State University</li><enter>

<li>2014 -- Graduate Research Paper of the Year, Department of Languages, Philosophy, and Communication Studies, Utah State University</li><enter>

<li>2013 -- Graduate Researcher of the Year, Department of Languages, Philosophy, and Communication Studies, Utah State University </li><enter>
</ol>
<center  style="font-size:20px">PROFESSIONAL AFFILIATIONS</center><enter>
<ul>
<li>Japanese Association of Language Teaching (JALT) </li>

<li>International Association for Language Learning Technology (IALLT) </li>

<li>Ludic Language Pedagogy (LLP) </li>

<li>American Educational Research Association (AERA) </li>

<li>Computer Assisted Language Instruction Consortium (CALICO)</li><enter>

<li>American Association of Applied Linguistics (AAAL) </li><enter>

<li>American Council on The Teaching of Foreign Languages (ACTFL) </li><enter>

<li>Chinese Language Teachers Association (CLTA)</li><enter>

<li>Teachers of English to Speakers of Other Languages Association (TESOL)</li><enter>

<li>Utah Foreign Language Association (UFLA) </li><enter>
</ul>

<center  style="font-size:20px">LANGUAGES</center><enter>
<ul>
<li>English – Native </li><enter>
<li>Chinese (Mandarin) – Near-native </li><enter>
<li>Spanish – Advanced </li><enter>
</ul>
<hr>
<hr>
</div>